### PR TITLE
Export list error reordered commits

### PR DESCRIPTION
**Pull request by mitchdraft**

### CODE REVIEW

**Comment by mitchdraft** [comment]
@ilackarms a lot of the diffs have nothing to do with this change, so I reworked the commit order from https://github.com/solo-io/solo-kit/pull/125 and now:
- 1st commit regens resources from unchanged master repo after dep ensure
- 2nd commit `apply change: export list error as string` has new content - please direct your attention there

**Comment by ilackarms** [comment]
@mitchdraft this looks fine to me, but wondering what purpose this change is for?

**Comment by mitchdraft** [comment]
slightly better error handling for user-facing cli output https://github.com/solo-io/solo-kit/issues/122#issuecomment-480489370

**Comment by mitchdraft** [comment]
if we find more of a need for this in the future, we can add it then. Utility seems too limited to add to all projects

**Pull request closed without merging**
